name: .NET Core Desktop

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Restore the application
      run: dotnet restore Weedwacker.sln
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application
      run: dotnet build -c $env:Configuration Weedwacker.sln
      env:
        Configuration: ${{ matrix.configuration }}
    
    - name: Upload the binaries
      uses: actions/upload-artifact@v2
      with:
        name: Weedwacker-${{ matrix.configuration }}
        path: bin/*

